# Generated by Django 3.2.6 on 2022-04-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='area_of_interest',
            field=models.ManyToManyField(blank=True, related_name='account', to='accounts.Interest'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='users_document',
            field=models.ManyToManyField(blank=True, related_name='documents', to='accounts.Document'),
        ),
    ]
