# Generated by Django 3.2.6 on 2022-04-19 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_accounts_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('id',)},
        ),
    ]
