# Generated by Django 3.2.6 on 2022-04-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_document_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='files',
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(default=2, upload_to='documents'),
            preserve_default=False,
        ),
    ]
